### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by DawidMazur** [ahmedesa/laravel-api-tool-kit#29]
Hey

Can you refine the data types accepted by the methods in ApiResponse?

For example:

```        
if($validateUser->fails()){
      return $this->responseBadRequest($validateUser->errors(), 'Validation Error');
}
```

Larastan returns:
phpstan: Parameter #1 $details of method App\Http\Controllers\Api\V1\Auth\RegisterController::responseBadRequest() expects null, Illuminate\Support\MessageBag given.
phpstan: Parameter #2 $message of method App\Http\Controllers\Api\V1\Auth\RegisterController::responseBadRequest() expects null, string given.

![image](https://github.com/ahmedesa/laravel-api-tool-kit/assets/50441054/2c7ec1ae-6999-47fe-8c4e-2ba0c9d683ca)

The IDE states that the only allowed type is null, of course the code works, but it causes errors in larastan which doesn't help in maintaining good quality of the code, if I'm wrong and it can be set properly please let me know how.

**Comment by ahmedesa** [comment]
Thank you for your report.

The issue you mentioned about type hinting in ApiResponse methods has been resolved. This was happening due to PHP 7.4's type hinting limitations, leading to errors flagged by Larastan.

To fix this, I've updated the package to support PHP versions 8 and above. For more details, you can review the changes in commit [9b959e](https://github.com/ahmedesa/laravel-api-tool-kit/commit/9b959e51ea3a4ec75c88898744525f9864ec20ca)  tagged under version [2.0.0](https://github.com/ahmedesa/laravel-api-tool-kit/releases/tag/2.0.0).
