### ISSUE TITLE
Standardize Error Responses

### ISSUE THREAD

**Issue by iamnomana** [ahmedesa/laravel-api-tool-kit#33]
I've noticed that changing the exception handler from "ExceptionHandler" to "APIHandler", it works fine on dev mode, but when it goes into production mode, I only receive server error with code 500 instead of the actual error. Which sometimes is a Validator error.

Kindly explain why it's so.

By the way, I love this package. Greate job.🫱🏼‍🫲🏽

**Comment by ahmedesa** [comment]
It seems  you are talking about query exceptions , The reason behind this behavior is that showing detailed query exceptions in the error response in production could pose a security risk, as it might reveal sensitive information about your database structure. To avoid this, query exceptions are not directly shown to users in production. Instead, you can find these errors in the log files. While it's possible to customize the way query exceptions are handled and returned, it's generally not recommended due to the security implications.

**Comment by iamnomana** [comment]
Okay that's understandable. Thank you brother.
